name: CD

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'The image tag for deployment'
        required: true
        type: string

env:
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

jobs:
  prepare-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev-testapp]
        location: [westeurope]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform plan
        run: terraform plan -out=tfplan
        working-directory: terraform
        env:
          TF_VAR_subscription_id: ${{ env.ARM_SUBSCRIPTION_ID }}
          TF_VAR_client_id: ${{ env.ARM_CLIENT_ID }}
          TF_VAR_client_secret: ${{ env.ARM_CLIENT_SECRET }}
          TF_VAR_tenant_id: ${{ env.ARM_TENANT_ID }}
          TF_VAR_environment: ${{ matrix.environment }}
          TF_VAR_location: ${{ matrix.location }}
          TF_VAR_image_tag: ${{ github.event.inputs.image_tag }}

      - name: Show Terraform plan
        run: terraform show tfplan
        working-directory: terraform

      - name: Upload plan as artifact
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: terraform/tfplan

  deploy:
    needs: prepare-deploy
    runs-on: ubuntu-latest
    environment: 'main'
    steps:
      - uses: actions/checkout@v4

      - name: Download plan artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: terraform/

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply tfplan
        working-directory: terraform
