name: CI

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install test dependencies
        run: pip install flake8 httpx pytest

      - name: Lint code
        run: flake8 app

      - name: Install app dependencies
        run: pip install -r app/requirements.txt

      - name: Run tests
        run: pytest app
  build-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev-testapp]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: filiptestapp.azurecr.io
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t filiptestapp.azurecr.io/${{ matrix.environment }}-image:${GITHUB_RUN_ID} app
          docker push filiptestapp.azurecr.io/${{ matrix.environment }}-image:${GITHUB_RUN_ID}

      - name: Save the IMAGE_TAG
        run: echo "IMAGE_TAG=${GITHUB_RUN_ID}"

  terraform-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init for validation
        run: terraform init -backend=false
        working-directory: terraform

      - name: Terraform checks
        run: |
          terraform fmt -check
          terraform validate
        working-directory: terraform

      - name: Terraform lint
        run: |
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          tflint --chdir=terraform/

      - name: Run Terraform Sec
        run: |
          curl -s https://raw.githubusercontent.com/aquasecurity/tfsec/master/scripts/install_linux.sh | bash
          tfsec terraform/
