name: CI

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Debug IMAGE_TAG
        run: echo "IMAGE_TAG is $CONTAINER_IMAGE_TAG"

      - name: Debug IMAGE_TAG 2
        run: echo "IMAGE_TAG is ${{ env.CONTAINER_IMAGE_TAG }}"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install test dependencies
        run: pip install flake8 httpx pytest

      - name: Lint code
        run: flake8 app

      - name: Install app dependencies
        run: pip install -r app/requirements.txt

      - name: Run tests
        run: pytest app
  build-image:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev-testapp]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v2
        with:
          login-server: filiptestapp.azurecr.io
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          IMAGE_TAG=${GITHUB_SHA}
          docker build -t filiptestapp.azurecr.io/${{ matrix.environment }}-image:${IMAGE_TAG} app
          docker push filiptestapp.azurecr.io/${{ matrix.environment }}-image:${IMAGE_TAG}

      - name: Save the IMAGE_TAG to the output
        run: echo "IMAGE_TAG=${IMAGE_TAG}" >> $GITHUB_OUTPUT
  terraform-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init for validation
        run: terraform init -backend=false
        working-directory: terraform

      - name: Terraform checks
        run: |
          terraform fmt -check
          terraform validate
        #terraform sec
        working-directory: terraform
